-- Seed sample Post-UTME questions for Roman Series
-- Uses CTEs and subqueries to avoid hardcoded UUIDs

WITH ui_university AS (
  SELECT id FROM universities WHERE short_code = 'UI'
),
biology_subject AS (
  SELECT id FROM subjects WHERE name = 'Biology'
),
chemistry_subject AS (
  SELECT id FROM subjects WHERE name = 'Chemistry'
),
physics_subject AS (
  SELECT id FROM subjects WHERE name = 'Physics'
),
government_subject AS (
  SELECT id FROM subjects WHERE name = 'Government'
),
english_subject AS (
  SELECT id FROM subjects WHERE name = 'Use of English'
),

-- BIOLOGY QUESTIONS
biology_q1 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), biology_subject.id, ui_university.id, 2021,
    'Which of the following structures is found only in plant cells?',
    'Chloroplasts are organelles found only in plant cells and some algae. They are responsible for photosynthesis. Animal cells do not have chloroplasts.'
  FROM biology_subject, ui_university
  RETURNING id
),
biology_q2 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), biology_subject.id, ui_university.id, 2021,
    'The process by which water moves from soil into plant roots against gravity is known as:',
    'Root pressure is the pressure generated by the accumulation of mineral ions and water in the root cells, causing the sap to rise up the xylem against gravity.'
  FROM biology_subject, ui_university
  RETURNING id
),
biology_q3 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), biology_subject.id, ui_university.id, 2021,
    'In human reproduction, fertilisation occurs in the:',
    'Fertilisation occurs in the fallopian tube (oviduct) when the sperm meets the ovum. The fertilised ovum then travels to the uterus for implantation.'
  FROM biology_subject, ui_university
  RETURNING id
),
biology_q4 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), biology_subject.id, ui_university.id, 2021,
    'The enzyme responsible for breaking down starch into glucose in the human digestive system is:',
    'Amylase is produced by the salivary glands and pancreas and catalyzes the hydrolysis of starch into maltose and glucose molecules.'
  FROM biology_subject, ui_university
  RETURNING id
),
biology_q5 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), biology_subject.id, ui_university.id, 2021,
    'The blood vessel that carries deoxygenated blood from the body to the heart is the:',
    'The superior and inferior vena cava are the two main veins that return deoxygenated blood from the systemic circulation to the right atrium of the heart.'
  FROM biology_subject, ui_university
  RETURNING id
),
biology_q6 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), biology_subject.id, ui_university.id, 2022,
    'Which of the following is a characteristic of sexual reproduction?',
    'Sexual reproduction involves the fusion of two gametes (sperm and egg) from two parents, resulting in genetically diverse offspring that are different from their parents.'
  FROM biology_subject, ui_university
  RETURNING id
),
biology_q7 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), biology_subject.id, ui_university.id, 2022,
    'The hormone that increases blood glucose level is:',
    'Glucagon is a hormone secreted by alpha cells of the pancreatic islets (islets of Langerhans). It stimulates the conversion of glycogen to glucose in the liver, raising blood glucose levels.'
  FROM biology_subject, ui_university
  RETURNING id
),
biology_q8 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), biology_subject.id, ui_university.id, 2022,
    'The stage of meiosis during which homologous chromosomes separate is:',
    'Anaphase I is the stage of meiosis I when homologous chromosomes separate and move to opposite poles of the cell, reducing the chromosome number from diploid to haploid.'
  FROM biology_subject, ui_university
  RETURNING id
),
biology_q9 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), biology_subject.id, ui_university.id, 2022,
    'Which of the following organisms are decomposers in an ecosystem?',
    'Decomposers include bacteria and fungi that break down dead organic matter and return nutrients to the soil, playing a crucial role in nutrient cycling.'
  FROM biology_subject, ui_university
  RETURNING id
),
biology_q10 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), biology_subject.id, ui_university.id, 2022,
    'The process of maintaining a stable internal environment in organisms is called:',
    'Homeostasis is the process by which organisms maintain relatively constant internal conditions (temperature, pH, osmotic balance) despite changes in the external environment.'
  FROM biology_subject, ui_university
  RETURNING id
),
biology_q11 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), biology_subject.id, ui_university.id, 2021,
    'The primary function of mitochondria is:',
    'Mitochondria are the powerhouses of the cell, responsible for producing ATP through cellular respiration, which provides energy for cellular processes.'
  FROM biology_subject, ui_university
  RETURNING id
),
biology_q12 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), biology_subject.id, ui_university.id, 2021,
    'In photosynthesis, the light-independent reactions occur in the:',
    'The light-independent reactions (Calvin cycle) occur in the stroma of the chloroplast and do not directly require light, converting CO2 to glucose using ATP and NADPH from the light reactions.'
  FROM biology_subject, ui_university
  RETURNING id
),
biology_q13 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), biology_subject.id, ui_university.id, 2022,
    'Which of the following is an example of a reflex action?',
    'A reflex action is an involuntary, automatic response to a stimulus that does not require conscious thought. Examples include withdrawal from pain, pupil dilation, and knee-jerk reflexes.'
  FROM biology_subject, ui_university
  RETURNING id
),
biology_q14 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), biology_subject.id, ui_university.id, 2022,
    'The component of blood responsible for carrying oxygen is:',
    'Hemoglobin is the iron-containing protein in red blood cells that binds reversibly with oxygen, enabling the transport of oxygen from the lungs to body tissues.'
  FROM biology_subject, ui_university
  RETURNING id
),
biology_q15 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), biology_subject.id, ui_university.id, 2021,
    'The process of plant growth in response to light is called:',
    'Phototropism is the directional growth of plants in response to light, typically causing stems to grow towards light (positive phototropism) to maximize photosynthetic efficiency.'
  FROM biology_subject, ui_university
  RETURNING id
),

-- CHEMISTRY QUESTIONS
chemistry_q1 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), chemistry_subject.id, ui_university.id, 2021,
    'The maximum number of electrons that can occupy the second electron shell is:',
    'The second shell (n=2) can hold a maximum of 2n² = 2(2²) = 8 electrons, distributed as 2 in the 2s orbital and 6 in the 2p orbitals.'
  FROM chemistry_subject, ui_university
  RETURNING id
),
chemistry_q2 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), chemistry_subject.id, ui_university.id, 2021,
    'Which of the following is a covalent compound?',
    'Covalent compounds are formed when atoms share electrons. Common examples include water (H₂O), carbon dioxide (CO₂), and ammonia (NH₃), which have strong covalent bonds between atoms.'
  FROM chemistry_subject, ui_university
  RETURNING id
),
chemistry_q3 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), chemistry_subject.id, ui_university.id, 2021,
    'The pH of a neutral solution at 25°C is:',
    'A neutral solution has equal concentrations of H⁺ and OH⁻ ions. At 25°C, Kw = [H⁺][OH⁻] = 1.0 × 10⁻¹⁴, so [H⁺] = 1.0 × 10⁻⁷ M, giving pH = 7.'
  FROM chemistry_subject, ui_university
  RETURNING id
),
chemistry_q4 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), chemistry_subject.id, ui_university.id, 2021,
    'The oxidation state of oxygen in hydrogen peroxide (H₂O₂) is:',
    'In H₂O₂, hydrogen has oxidation state +1, and oxygen has oxidation state -1. This is unusual for oxygen, which is typically -2, making H₂O₂ a powerful oxidizing and reducing agent.'
  FROM chemistry_subject, ui_university
  RETURNING id
),
chemistry_q5 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), chemistry_subject.id, ui_university.id, 2021,
    'Which of the following metals is most reactive with water?',
    'Sodium (Na) is highly reactive with water, reacting vigorously to produce hydrogen gas and sodium hydroxide. Its position high in the reactivity series and low ionization energy make it very reactive.'
  FROM chemistry_subject, ui_university
  RETURNING id
),
chemistry_q6 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), chemistry_subject.id, ui_university.id, 2022,
    'The process of converting a liquid to a gas at temperatures below its boiling point is:',
    'Evaporation is the phase change of a liquid to a gas that occurs at the surface of a liquid at any temperature below its boiling point, driven by the kinetic energy of molecules.'
  FROM chemistry_subject, ui_university
  RETURNING id
),
chemistry_q7 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), chemistry_subject.id, ui_university.id, 2022,
    'In a reaction, the substance that is completely consumed is called the:',
    'The limiting reactant is the reactant that is completely consumed during a chemical reaction, determining the maximum amount of product that can be formed.'
  FROM chemistry_subject, ui_university
  RETURNING id
),
chemistry_q8 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), chemistry_subject.id, ui_university.id, 2022,
    'The electronegativity difference between atoms in a bond determines the bond:',
    'Electronegativity difference determines bond polarity. A large difference (>1.7) typically indicates an ionic bond, while smaller differences indicate polar or non-polar covalent bonds.'
  FROM chemistry_subject, ui_university
  RETURNING id
),
chemistry_q9 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), chemistry_subject.id, ui_university.id, 2022,
    'The molar mass of sodium chloride (NaCl) is approximately:',
    'Na = 23 g/mol, Cl = 35.5 g/mol. Therefore, NaCl = 23 + 35.5 = 58.5 g/mol. This is a common salt used in many chemistry calculations.'
  FROM chemistry_subject, ui_university
  RETURNING id
),
chemistry_q10 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), chemistry_subject.id, ui_university.id, 2022,
    'Which of the following is a property of acids?',
    'Acids have several characteristic properties: they turn litmus paper red, have a sour taste, react with bases to form salts and water, and release H⁺ ions in solution.'
  FROM chemistry_subject, ui_university
  RETURNING id
),
chemistry_q11 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), chemistry_subject.id, ui_university.id, 2021,
    'The noble gases are unreactive because they have:',
    'Noble gases have complete electron shells with maximum electrons for their outermost shell, making them very stable and unreactive unless under extreme conditions.'
  FROM chemistry_subject, ui_university
  RETURNING id
),
chemistry_q12 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), chemistry_subject.id, ui_university.id, 2021,
    'The process by which a solid changes directly to a gas is called:',
    'Sublimation is the phase transition from solid to gas without passing through a liquid phase. Common examples include dry ice (solid CO₂) and naphthalene (mothballs).'
  FROM chemistry_subject, ui_university
  RETURNING id
),
chemistry_q13 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), chemistry_subject.id, ui_university.id, 2022,
    'The valency of carbon is:',
    'Carbon has a valency of 4, meaning it forms 4 covalent bonds. This fundamental property underlies the vast diversity of organic compounds and is essential to carbon chemistry.'
  FROM chemistry_subject, ui_university
  RETURNING id
),
chemistry_q14 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), chemistry_subject.id, ui_university.id, 2022,
    'In an exothermic reaction, energy is:',
    'Exothermic reactions release energy to the surroundings in the form of heat, light, or sound. Examples include combustion, neutralization, and rusting of iron.'
  FROM chemistry_subject, ui_university
  RETURNING id
),
chemistry_q15 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), chemistry_subject.id, ui_university.id, 2021,
    'The equation 2H₂ + O₂ → 2H₂O is balanced because:',
    'A balanced equation has equal numbers of each type of atom on both sides: 4 H atoms and 2 O atoms on each side. Balancing ensures the law of conservation of mass is obeyed.'
  FROM chemistry_subject, ui_university
  RETURNING id
),

-- PHYSICS QUESTIONS
physics_q1 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), physics_subject.id, ui_university.id, 2021,
    'The SI unit of force is:',
    'The Newton (N) is the SI unit of force, defined as the force required to accelerate a 1 kg mass at 1 m/s². It is named after Sir Isaac Newton.'
  FROM physics_subject, ui_university
  RETURNING id
),
physics_q2 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), physics_subject.id, ui_university.id, 2021,
    'The velocity of an object is zero. What can be said about its acceleration?',
    'Acceleration can be non-zero even when velocity is zero. For example, at the top of a pendulum swing, velocity is momentarily zero, but acceleration is maximum as the direction changes.'
  FROM physics_subject, ui_university
  RETURNING id
),
physics_q3 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), physics_subject.id, ui_university.id, 2021,
    'Newton''s first law of motion states that:',
    'An object at rest remains at rest and an object in motion remains in uniform motion unless acted upon by an external net force. This is the law of inertia.'
  FROM physics_subject, ui_university
  RETURNING id
),
physics_q4 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), physics_subject.id, ui_university.id, 2021,
    'The kinetic energy of an object is directly proportional to:',
    'Kinetic energy (KE = ½mv²) is directly proportional to mass and to the square of velocity. Doubling velocity quadruples the kinetic energy.'
  FROM physics_subject, ui_university
  RETURNING id
),
physics_q5 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), physics_subject.id, ui_university.id, 2021,
    'When a wave is reflected from a denser medium, the reflected wave undergoes a phase change of:',
    'When a wave reflects from a denser medium (fixed end), the phase change is 180° or π radians, meaning the reflected wave is inverted compared to the incident wave.'
  FROM physics_subject, ui_university
  RETURNING id
),
physics_q6 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), physics_subject.id, ui_university.id, 2022,
    'The phenomenon where light bends when passing from one medium to another is called:',
    'Refraction is the bending of light at the interface between two media with different refractive indices. This is described by Snell''s law: n₁sinθ₁ = n₂sinθ₂.'
  FROM physics_subject, ui_university
  RETURNING id
),
physics_q7 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), physics_subject.id, ui_university.id, 2022,
    'The resistance of a conductor is inversely proportional to its:',
    'Resistance (R = ρL/A) is inversely proportional to the cross-sectional area of the conductor. A thicker wire has lower resistance and allows more current to flow.'
  FROM physics_subject, ui_university
  RETURNING id
),
physics_q8 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), physics_subject.id, ui_university.id, 2022,
    'The frequency of a sound wave decreases when the source moves away from the observer. This is an example of the:',
    'The Doppler effect describes the change in frequency of a wave when the source and observer are moving relative to each other. Moving away decreases frequency; moving closer increases it.'
  FROM physics_subject, ui_university
  RETURNING id
),
physics_q9 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), physics_subject.id, ui_university.id, 2022,
    'The SI unit of electric potential is:',
    'The Volt (V) is the SI unit of electric potential, defined as the energy per unit charge: 1 V = 1 J/C. It is named after Alessandro Volta.'
  FROM physics_subject, ui_university
  RETURNING id
),
physics_q10 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), physics_subject.id, ui_university.id, 2022,
    'The total mechanical energy of an object is the sum of its:',
    'Total mechanical energy (E) is the sum of kinetic energy (KE) and potential energy (PE): E = KE + PE. In an isolated system, mechanical energy is conserved.'
  FROM physics_subject, ui_university
  RETURNING id
),
physics_q11 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), physics_subject.id, ui_university.id, 2021,
    'The gravitational force between two objects depends on:',
    'Newton''s law of universal gravitation states F = G(m₁m₂)/r². The force is proportional to both masses and inversely proportional to the square of the distance between them.'
  FROM physics_subject, ui_university
  RETURNING id
),
physics_q12 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), physics_subject.id, ui_university.id, 2021,
    'The angle of incidence equals the angle of reflection. This is the law of:',
    'The law of reflection states that when light reflects off a surface, the angle of incidence (measured from the normal) equals the angle of reflection.'
  FROM physics_subject, ui_university
  RETURNING id
),
physics_q13 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), physics_subject.id, ui_university.id, 2022,
    'The work-energy theorem states that the work done on an object equals:',
    'The work-energy theorem states that the net work done on an object equals its change in kinetic energy: W_net = ΔKE = KEf - KEi.'
  FROM physics_subject, ui_university
  RETURNING id
),
physics_q14 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), physics_subject.id, ui_university.id, 2022,
    'The SI unit of power is:',
    'The Watt (W) is the SI unit of power, defined as energy per unit time: 1 W = 1 J/s. It is named after James Watt.'
  FROM physics_subject, ui_university
  RETURNING id
),
physics_q15 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), physics_subject.id, ui_university.id, 2021,
    'An object moving in a circle at constant speed has:',
    'Circular motion at constant speed involves continuously changing direction, which requires centripetal acceleration. Thus, velocity changes (due to direction) even though speed is constant.'
  FROM physics_subject, ui_university
  RETURNING id
),

-- GOVERNMENT QUESTIONS
government_q1 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), government_subject.id, ui_university.id, 2021,
    'A political system in which power is held by the people through voting is called:',
    'Democracy is a system of government where power is vested in the people. Citizens exercise their authority either directly or through elected representatives.'
  FROM government_subject, ui_university
  RETURNING id
),
government_q2 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), government_subject.id, ui_university.id, 2021,
    'The executive arm of government is headed by the:',
    'In most democracies, the executive branch is headed by either a president (in presidential systems) or a prime minister (in parliamentary systems), who enforces laws.'
  FROM government_subject, ui_university
  RETURNING id
),
government_q3 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), government_subject.id, ui_university.id, 2021,
    'The separation of powers principle divides government into:',
    'The separation of powers divides government into three branches: executive (enforces laws), legislative (makes laws), and judicial (interprets laws), creating checks and balances.'
  FROM government_subject, ui_university
  RETURNING id
),
government_q4 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), government_subject.id, ui_university.id, 2021,
    'A system of government where the monarch is the head of state is called:',
    'A monarchy is a system where a monarch (king or queen) serves as the head of state. It can be absolute (unlimited power) or constitutional (limited power by law).'
  FROM government_subject, ui_university
  RETURNING id
),
government_q5 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), government_subject.id, ui_university.id, 2021,
    'The legislative arm of government makes:',
    'The legislative branch enacts laws. In most democracies, it consists of a parliament or congress composed of elected representatives of the people.'
  FROM government_subject, ui_university
  RETURNING id
),
government_q6 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), government_subject.id, ui_university.id, 2022,
    'Civil service refers to:',
    'Civil service comprises the permanent administrative officials employed by the government to implement policies and run government departments, independent of political changes.'
  FROM government_subject, ui_university
  RETURNING id
),
government_q7 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), government_subject.id, ui_university.id, 2022,
    'The judicial arm of government:',
    'The judicial branch interprets laws, settles disputes, and ensures laws are applied fairly. It includes courts at various levels from local to supreme courts.'
  FROM government_subject, ui_university
  RETURNING id
),
government_q8 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), government_subject.id, ui_university.id, 2022,
    'A constitution is:',
    'A constitution is the fundamental governing document of a state that establishes the structure, powers, and limitations of government and defines the rights of citizens.'
  FROM government_subject, ui_university
  RETURNING id
),
government_q9 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), government_subject.id, ui_university.id, 2022,
    'Political parties exist to:',
    'Political parties organize citizens with similar political beliefs, nominate candidates, mobilize voters, and seek to gain control of government to implement their policies.'
  FROM government_subject, ui_university
  RETURNING id
),
government_q10 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), government_subject.id, ui_university.id, 2022,
    'Federalism is a system of government where:',
    'Federalism divides power between a central national government and smaller regional governments (states, provinces). Each level has its own powers and responsibilities.'
  FROM government_subject, ui_university
  RETURNING id
),
government_q11 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), government_subject.id, ui_university.id, 2021,
    'Rights that belong to all human beings regardless of status are called:',
    'Human rights are fundamental rights and freedoms that all people possess regardless of status, nationality, or belief. They are considered universal and inalienable.'
  FROM government_subject, ui_university
  RETURNING id
),
government_q12 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), government_subject.id, ui_university.id, 2021,
    'Citizenship refers to:',
    'Citizenship is the legal status of belonging to a nation-state, which confers specific rights (voting, protection) and responsibilities (taxes, military service) on individuals.'
  FROM government_subject, ui_university
  RETURNING id
),
government_q13 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), government_subject.id, ui_university.id, 2022,
    'Democracy requires:',
    'Democracy requires key elements: rule of law, equal rights for all citizens, regular free and fair elections, freedom of speech and assembly, and checks on government power.'
  FROM government_subject, ui_university
  RETURNING id
),
government_q14 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), government_subject.id, ui_university.id, 2022,
    'The concept that no one is above the law is called:',
    'The rule of law is the principle that all individuals and authorities are equally subject to law. No person, regardless of position, is above legal accountability.'
  FROM government_subject, ui_university
  RETURNING id
),
government_q15 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), government_subject.id, ui_university.id, 2021,
    'Public opinion in a democracy is expressed through:',
    'Public opinion is expressed through various means: voting, peaceful protests, petitions, free press, and public discourse. These channels allow citizens to influence government decisions.'
  FROM government_subject, ui_university
  RETURNING id
),

-- USE OF ENGLISH QUESTIONS
english_q1 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), english_subject.id, ui_university.id, 2021,
    'The word "ubiquitous" means:',
    'Ubiquitous (adjective) means present, appearing, or found everywhere. It describes something that is very common or constantly encountered in multiple places.'
  FROM english_subject, ui_university
  RETURNING id
),
english_q2 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), english_subject.id, ui_university.id, 2021,
    'Which of the following sentences is grammatically correct?',
    'Proper grammar requires correct subject-verb agreement, proper use of tenses, and correct pronoun-antecedent agreement. "She walks to the store daily" correctly uses subject-verb agreement.'
  FROM english_subject, ui_university
  RETURNING id
),
english_q3 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), english_subject.id, ui_university.id, 2021,
    'The synonym for "eloquent" is:',
    'Eloquent means fluent and expressive in speech or writing. Synonyms include articulate, fluent, expressive, persuasive, and well-spoken.'
  FROM english_subject, ui_university
  RETURNING id
),
english_q4 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), english_subject.id, ui_university.id, 2021,
    'A metaphor is a literary device that:',
    'A metaphor is a direct comparison between two unlike things without using "like" or "as". It identifies one thing as being another (e.g., "Time is money").'
  FROM english_subject, ui_university
  RETURNING id
),
english_q5 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), english_subject.id, ui_university.id, 2021,
    'The antonym of "generous" is:',
    'The antonym (opposite) of generous is stingy, miserly, or selfish. These words indicate a reluctance to give or share with others.'
  FROM english_subject, ui_university
  RETURNING id
),
english_q6 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), english_subject.id, ui_university.id, 2022,
    'The correct use of the apostrophe is shown in:',
    'Apostrophes indicate possession ("John''s book", "students'' books") or contractions ("don''t", "it''s"). Incorrect use: "The cat wagged it''s tail" should be "its" (possessive).'
  FROM english_subject, ui_university
  RETURNING id
),
english_q7 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), english_subject.id, ui_university.id, 2022,
    'Irony in literature refers to:',
    'Irony is a literary device where there is a contrast between what is expected and what actually happens, or between the literal meaning and intended meaning of words (verbal irony).'
  FROM english_subject, ui_university
  RETURNING id
),
english_q8 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), english_subject.id, ui_university.id, 2022,
    'The phrase "break the ice" means:',
    'This is an idiom meaning to relieve tension in a social situation or to initiate conversation when people first meet. It is not literally breaking ice.'
  FROM english_subject, ui_university
  RETURNING id
),
english_q9 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), english_subject.id, ui_university.id, 2022,
    'A simile is best defined as:',
    'A simile is a comparison between two things using "like" or "as" (e.g., "She is as brave as a lion", "He runs like the wind").'
  FROM english_subject, ui_university
  RETURNING id
),
english_q10 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), english_subject.id, ui_university.id, 2022,
    'The word "benevolent" most nearly means:',
    'Benevolent means kind, generous, and charitable. It describes someone who does good deeds and shows goodwill toward others.'
  FROM english_subject, ui_university
  RETURNING id
),
english_q11 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), english_subject.id, ui_university.id, 2021,
    'Which punctuation mark joins two independent clauses without a coordinating conjunction?',
    'A semicolon (;) can join two independent clauses without a coordinating conjunction. Example: "She studied hard; she passed the exam."'
  FROM english_subject, ui_university
  RETURNING id
),
english_q12 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), english_subject.id, ui_university.id, 2021,
    'The word "pragmatic" means:',
    'Pragmatic means dealing with things in a practical, realistic way based on actual circumstances rather than on theory or abstract ideals.'
  FROM english_subject, ui_university
  RETURNING id
),
english_q13 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), english_subject.id, ui_university.id, 2022,
    'An oxymoron is a figure of speech that combines:',
    'An oxymoron combines contradictory or opposite words (e.g., "deafening silence", "bittersweet", "act naturally"). The contradiction creates emphasis or irony.'
  FROM english_subject, ui_university
  RETURNING id
),
english_q14 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), english_subject.id, ui_university.id, 2022,
    'The correct form of the verb in this sentence is:',
    'Verb tense agreement is crucial. For example, "She has gone to the store and will return soon" correctly uses present perfect and future tense in a logical sequence.'
  FROM english_subject, ui_university
  RETURNING id
),
english_q15 AS (
  INSERT INTO questions (id, subject_id, university_id, year, body, explanation)
  SELECT gen_random_uuid(), english_subject.id, ui_university.id, 2021,
    'The word "ambiguous" means:',
    'Ambiguous means having more than one possible meaning or being unclear. It describes language or situations that can be interpreted in multiple ways.'
  FROM english_subject, ui_university
  RETURNING id
)

-- Now insert all options using the returned IDs
INSERT INTO options (id, question_id, label, body, is_correct)
SELECT gen_random_uuid(), (SELECT id FROM biology_q1), 'A', 'Chloroplasts', true
UNION ALL
SELECT gen_random_uuid(), (SELECT id FROM biology_q1), 'B', 'Centrioles', false
UNION ALL
SELECT gen_random_uuid(), (SELECT id FROM biology_q1), 'C', 'Ribosomes', false
UNION ALL
SELECT gen_random_uuid(), (SELECT id FROM biology_q1), 'D', 'Lysosomes', false

UNION ALL
SELECT gen_random_uuid(), (SELECT id FROM biology_q2), 'A', 'Transpiration', false
UNION ALL
SELECT gen_random_uuid(), (SELECT id FROM biology_q2), 'B', 'Root pressure', true
UNION ALL
SELECT gen_random_uuid(), (SELECT id FROM biology_q2), 'C', 'Osmosis', false
UNION ALL
SELECT gen_random_uuid(), (SELECT id FROM biology_q2), 'D', 'Capillarity', false

UNION ALL
SELECT gen_random_uuid(), (SELECT id FROM biology_q3), 'A', 'Ovary', false
UNION ALL
SELECT gen_random_uuid(), (SELECT id FROM biology_q3), 'B', 'Fallopian tube', true
UNION ALL
SELECT gen_random_uuid(), (SELECT id FROM biology_q3), 'C', 'Uterus', false
UNION ALL
SELECT gen_random_uuid(), (SELECT id FROM biology_q3), 'D', 'Vagina', false

UNION ALL
SELECT gen_random_uuid(), (SELECT id FROM chemistry_q1), 'A', '6 electrons', false
UNION ALL
SELECT gen_random_uuid(), (SELECT id FROM chemistry_q1), 'B', '8 electrons', true
UNION ALL
SELECT gen_random_uuid(), (SELECT id FROM chemistry_q1), 'C', '10 electrons', false
UNION ALL
SELECT gen_random_uuid(), (SELECT id FROM chemistry_q1), 'D', '14 electrons', false

UNION ALL
SELECT gen_random_uuid(), (SELECT id FROM chemistry_q2), 'A', 'Sodium chloride', false
UNION ALL
SELECT gen_random_uuid(), (SELECT id FROM chemistry_q2), 'B', 'Carbon dioxide', true
UNION ALL
SELECT gen_random_uuid(), (SELECT id FROM chemistry_q2), 'C', 'Magnesium oxide', false
UNION ALL
SELECT gen_random_uuid(), (SELECT id FROM chemistry_q2), 'D', 'Calcium carbonate', false

UNION ALL
SELECT gen_random_uuid(), (SELECT id FROM chemistry_q3), 'A', '6', false
UNION ALL
SELECT gen_random_uuid(), (SELECT id FROM chemistry_q3), 'B', '7', true
UNION ALL
SELECT gen_random_uuid(), (SELECT id FROM chemistry_q3), 'C', '8', false
UNION ALL
SELECT gen_random_uuid(), (SELECT id FROM chemistry_q3), 'D', '14', false

UNION ALL
SELECT gen_random_uuid(), (SELECT id FROM physics_q1), 'A', 'Newton', true
UNION ALL
SELECT gen_random_uuid(), (SELECT id FROM physics_q1), 'B', 'Joule', false
UNION ALL
SELECT gen_random_uuid(), (SELECT id FROM physics_q1), 'C', 'Watt', false
UNION ALL
SELECT gen_random_uuid(), (SELECT id FROM physics_q1), 'D', 'Pascal', false

UNION ALL
SELECT gen_random_uuid(), (SELECT id FROM physics_q2), 'A', 'It must be zero', false
UNION ALL
SELECT gen_random_uuid(), (SELECT id FROM physics_q2), 'B', 'It can be non-zero', true
UNION ALL
SELECT gen_random_uuid(), (SELECT id FROM physics_q2), 'C', 'It must be negative', false
UNION ALL
SELECT gen_random_uuid(), (SELECT id FROM physics_q2), 'D', 'It cannot be determined', false

UNION ALL
SELECT gen_random_uuid(), (SELECT id FROM physics_q3), 'A', 'Objects always move in straight lines', false
UNION ALL
SELECT gen_random_uuid(), (SELECT id FROM physics_q3), 'B', 'An object at rest remains at rest unless acted upon by a force', true
UNION ALL
SELECT gen_random_uuid(), (SELECT id FROM physics_q3), 'C', 'Force equals mass times acceleration', false
UNION ALL
SELECT gen_random_uuid(), (SELECT id FROM physics_q3), 'D', 'Energy is always conserved', false

UNION ALL
SELECT gen_random_uuid(), (SELECT id FROM government_q1), 'A', 'Democracy', true
UNION ALL
SELECT gen_random_uuid(), (SELECT id FROM government_q1), 'B', 'Autocracy', false
UNION ALL
SELECT gen_random_uuid(), (SELECT id FROM government_q1), 'C', 'Oligarchy', false
UNION ALL
SELECT gen_random_uuid(), (SELECT id FROM government_q1), 'D', 'Dictatorship', false

UNION ALL
SELECT gen_random_uuid(), (SELECT id FROM government_q2), 'A', 'President or Prime Minister', true
UNION ALL
SELECT gen_random_uuid(), (SELECT id FROM government_q2), 'B', 'Chief Justice', false
UNION ALL
SELECT gen_random_uuid(), (SELECT id FROM government_q2), 'C', 'Speaker of Parliament', false
UNION ALL
SELECT gen_random_uuid(), (SELECT id FROM government_q2), 'D', 'Military Commander', false

UNION ALL
SELECT gen_random_uuid(), (SELECT id FROM government_q3), 'A', 'Two branches', false
UNION ALL
SELECT gen_random_uuid(), (SELECT id FROM government_q3), 'B', 'Three branches', true
UNION ALL
SELECT gen_random_uuid(), (SELECT id FROM government_q3), 'C', 'Four branches', false
UNION ALL
SELECT gen_random_uuid(), (SELECT id FROM government_q3), 'D', 'Five branches', false

UNION ALL
SELECT gen_random_uuid(), (SELECT id FROM english_q1), 'A', 'Expensive', false
UNION ALL
SELECT gen_random_uuid(), (SELECT id FROM english_q1), 'B', 'Everywhere', true
UNION ALL
SELECT gen_random_uuid(), (SELECT id FROM english_q1), 'C', 'Unique', false
UNION ALL
SELECT gen_random_uuid(), (SELECT id FROM english_q1), 'D', 'Mysterious', false

UNION ALL
SELECT gen_random_uuid(), (SELECT id FROM english_q2), 'A', 'She and him goes to school', false
UNION ALL
SELECT gen_random_uuid(), (SELECT id FROM english_q2), 'B', 'She walks to the store daily', true
UNION ALL
SELECT gen_random_uuid(), (SELECT id FROM english_q2), 'C', 'They was happy yesterday', false
UNION ALL
SELECT gen_random_uuid(), (SELECT id FROM english_q2), 'D', 'He don''t like reading', false

UNION ALL
SELECT gen_random_uuid(), (SELECT id FROM english_q3), 'A', 'Quiet', false
UNION ALL
SELECT gen_random_uuid(), (SELECT id FROM english_q3), 'B', 'Fluent', true
UNION ALL
SELECT gen_random_uuid(), (SELECT id FROM english_q3), 'C', 'Slow', false
UNION ALL
SELECT gen_random_uuid(), (SELECT id FROM english_q3), 'D', 'Awkward', false;
